### ISSUE TITLE
I can't copy from the input field.

### ISSUE THREAD

**Issue by ryanholte** [tavosansal/epocha#1]
![new_issue_ _tavosansal_epocha](https://cloud.githubusercontent.com/assets/3150348/21271761/de0eddb2-c381-11e6-8d06-bcb880f8d7ba.jpg)

When I cmd+c on the timestamp the value isn't copied to my clipbaord

**Comment by tavosansal** [comment]
Electron limitation...I can look into it

**Comment by tavosansal** [comment]
Should be solved by v1.1.0 ... go here to download: https://github.com/tavosansal/epocha/releases/download/v1.1.0/epocha.zip
